
package com.starlc.common;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
/**
 * xx
 *
 * @author starlc
 * @since jdk1.7
 * @version 2017年11月30日 starlc
 */
public class App {

    /**
     * xx
     *
     * @return xx
     */
    public String getGreeting() {
        return "Hello world.";
    }

    /**
     * xx
     *
     * @param args xx
     */
    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
