/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import static org.junit.Assert.assertNotNull;

import org.junit.Test;

import com.starlc.common.App;

import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;

/**
 * xx
 *
 * @author starlc
 * @since jdk1.6
 * @version 2017年11月30日 starlc
 */
public class AppTest {
    
    /**
     * xx
     */
    @Test
    public void testAppHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());

        String dt = "201906";
        DateFormat df = new SimpleDateFormat("yyyyMM");
        try {
            Date date = df.parse(dt);
            System.out.println(new SimpleDateFormat("yyyy-MM-dd").format(date));
        } catch (ParseException e) {
            e.printStackTrace();
        }



    }
}
